### ISSUE TITLE
Part substitution causes crash

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#478]
### Part substitution cause crash
This piece of code does not work anymore in 2.4.0
```
0 !LPUB PLI BEGIN SUB torso1.ldr 16
0 !LPUB PART BEGIN IGN
1 16 0 -48 0 1 0 0 0 1 0 0 0 1 torso1.ldr
0 !LPUB PLI END
0 !LPUB PART END
```

### Environment
* Version of LPub3D - 2.4.0
* Windows 10

### Steps to reproduce
Encountering some parts that need to be treated as a part, right-click and choose "Treat as a part"

### Expected behavior
The individual parts should be treated as one part (like a minifig torso made from a torso, arms and hands)

### Actual behavior
LPub3D crashes.

### Workaround
Non found. Adding the appropriate lines manually causes an immediate crash upon opening the page

### Solution suggestion
Please fix part substitution

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

I could only reproduce this behaviour with custom parts that have an _underscore_ `_` in the name - e.g. Wing_R.ldr. As you know, the _underscore_ `_` is used to append image attributes to the part+color nameKey. These attributes are reflected in the part image name. When an _underscore_ is used in the part name as exampled above, the attributes are offset and this causes the application to abnormal end when parsing the nameKey. This behaviour has been corrected. When _underscores_ are not used in the part name, as in the example you shared, I could not reproduce this behaviour.

![Screenshot - 12_11_2020 , 03_09_02](https://user-images.githubusercontent.com/13388970/98887315-0a36f400-2496-11eb-9afc-327be5c61537.png)

![Screenshot - 12_11_2020 , 03_10_27](https://user-images.githubusercontent.com/13388970/98887334-1622b600-2496-11eb-940a-078c5a3808a8.png)

Cheers,

**Comment by jacovandermolen** [comment]
Hmm, OK. I am 100% sure I have no underscores in filenames.
Here is the log file and the attached model file.
I tried to treat the torso for the minifig as a part. Then crash.

[minifig.mpd.txt](https://github.com/trevorsandy/lpub3d/files/5529003/minifig.mpd.txt)

[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/5528987/LPub3DLog.txt)

**Comment by trevorsandy** [comment]
It is possible that a previous fix in my maintenance environment may have corrected the behaviour you are experiencing.

The minifig.mpd sample file does not produce the described behaviour on my latest maintenance build.

![Screenshot - 12_11_2020 , 23_51_29](https://user-images.githubusercontent.com/13388970/99006487-d5cd4180-2542-11eb-8cfd-2bc74c480048.png)

![Screenshot - 12_11_2020 , 23_53_01](https://user-images.githubusercontent.com/13388970/99006515-debe1300-2542-11eb-9f22-12584e66b0b0.png)

Cheers,

**Comment by jacovandermolen** [comment]
Sorry, but I still experience this crash in 2.4.0.195.2415_20201123 too.

**Comment by jacovandermolen** [comment]
Model file:
```
0 FILE main.ldr
[LPub3DLog - kopie.txt](https://github.com/trevorsandy/lpub3d/files/5585606/LPub3DLog.-.kopie.txt)

0 Minifig
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE
0 !LPUB PLI BEGIN SUB torso.ldr 16
0 !LPUB PART BEGIN IGN
1 16 -23.688 26.76 -9.884 1 0 0 0 1 0 0 0 1 torso.ldr
0 !LPUB PLI END
0 !LPUB PART END
1 14 0 -24 0 1 0 0 0 1 0 0 0 1 3626bp01.dat
1 70 0 32 0 1 0 0 0 1 0 0 0 1 3815c01.dat
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 86035.dat
0 NOFILE 
0 FILE torso.ldr
0 Name: torso.ldr
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
1 14 0 0 0 0.985 0.12 0.12 -0.002 0.717 -0.697 -0.17 0.686 0.707 3820.dat
1 1 23.688 -26.76 9.884 1 0 0 0 1 0 0 0 1 973.dat
1 1 8.136 -17.76 9.884 0.985 -0.17 0 0.17 0.985 0 0 0 1 3818.dat
1 1 39.239 -17.76 9.884 0.985 0.17 0 -0.17 0.985 0 0 0 1 3819.dat
1 14 47.375 0 0 0.985 0.12 -0.12 -0.17 0.697 -0.697 0 0.707 0.707 3820.dat
0 NOFILE 

```
Log file attached.
Opening this model immediately crashes LPub3D all versions 2.4.x

**Comment by trevorsandy** [comment]
Hi Jaco, 

Thank you for reporting this behaviour. I’ll take a look. 

Obviously, this abnormal end is not related to the _Treat as Part_ menu option if it presents on opening the model file. 

I suspect the `0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE` command may be triggering this behaviour. If the behaviour does not present without this command, this should be a new ticket.

Cheers

**Comment by jacovandermolen** [comment]
It occurs with or without 0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE.
The model file I open is done with a previous version of LPub3D.

If I remove this piece of coding
```
0 !LPUB PLI BEGIN SUB torso.ldr 16
0 !LPUB PART BEGIN IGN
1 16 -23.688 26.76 -9.884 1 0 0 0 1 0 0 0 1 torso.ldr
0 !LPUB PLI END
0 !LPUB PART END
```
I can open the file in 2.4.x but if I choose Treat as Part a crash occurs without any warning or errors.
The image file for the torso (body, arms and hands) is created though. 
I just seems then the page cannot finish rendering the complete torso in the PLI.

**Comment by trevorsandy** [comment]
Ok - The problem seems to stem from the Native renderer. 

I was able to reproduce it after looking at your log and observing the only difference was the renderer. When I set the renderer to Native and attempt to open your example, the behaviour is as you described. This is a good step forward.

Cheers,

**Comment by jacovandermolen** [comment]
Ah, OK. I should have mentioned that ;-)
I rarely use LDView lately since the native renderer now supports texture mapping and handles camera angles and distance much better than before. I have great results now with it.

To verify: using LDView the Treat as part option indeed works just fine :-)

**Comment by trevorsandy** [comment]
This behaviour has been corrected. 

Basically the native renderer crashes when a top model and submodel shares the same name. This would be the case for a submodel being treated as a part because when I marshall the part's content for the renderer, the content is configured as an mpd file and submitted to the renderer. 

I've implemented a control for pli parts to ensure their native viewer content is never configured with the same main model and submodel names when the part is a substitute or converted submodel.

Cheers,
