### ISSUE TITLE
Abnormal message when loading the model

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#724]
### Subject
When loading the model, this message is shown.
But only if the submodel 328 is inserted first.
I have already checked the model file in the text editor, but did not find anything unusual.

### Environment
* Version of LPub3D - 2.4.6r324 mobile version
* Operating system - Win11

![2023-06-15 18_18_41-LPub3D Error](https://github.com/trevorsandy/lpub3d/assets/49073781/30e59914-765b-4cfd-ad8b-4e5db2537855)

I'll send you a mail with the model file.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Indeed. I encountered this behaviour during regression testing. The correction is in the next release build.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour is corrected.

Ticket _Inconsistent page loading and numbering #693_

Commit _Build modification - refactor parsing multi-step callout #693_ 7eac984

Cheers,

**Comment by technicbasics** [comment]
Thanks!
Is this behaviour already corrected in the last continuous build r352?

**Comment by trevorsandy** [comment]
> Is this behaviour already corrected in the last continuous build r352?

Yes it is.

Cheers,

**Comment by technicbasics** [comment]
Strange, I still get the message... 🤔Am 17.06.23, 23:06 schrieb Trevor SANDY ***@***.***>:

   
   
   Is this behaviour already corrected in the last continuous build r352? 
   
  Yes it is. 
  Cheers,

**Comment by trevorsandy** [comment]
> Strange, I still get the message...

Very well. I’ll take a look. Did you send your model file by email ?

Cheers,

**Comment by trevorsandy** [comment]
I have made another attempt to correct this behavior as I was able to reproduce it with your model file.

With the checked in update, I was able to load your file, navigate past the cover page and load the first multi-step page without any unexpected behaviour.

Let me know if you continue to experience this behaviour with the latest release - r354.

Cheers,
